Repository MLH-Fellowship/spotify-web-app, pull requests merged in 2021-08, with the labels that each got.

#4 Create front and back skeletons
  .gitignore
  backend/app/__init__.py
  backend/requirements.txt
  backend/wsgi.py
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
Labels: enhancement

#7 Create Welcome Page with Spotify Login
  .gitignore
  backend/app/__init__.py
  backend/requirements.txt
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/auth/Auth.js
  frontend/src/auth/Spotify.js
  frontend/src/index.css
  frontend/src/layouts/Home/index.js
  frontend/src/layouts/Login/index.js
  frontend/src/layouts/Welcome/index.js
  frontend/src/layouts/Welcome/welcome.scss
  frontend/src/logo.svg
  frontend/src/routing/PrivateRoute.js
  frontend/src/routing/PublicRoute.js
Labels: enhancement

#9 8 Spotify insights
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/auth/Auth.js
  frontend/src/auth/Spotify.js
  frontend/src/layouts/Home/home.scss
  frontend/src/layouts/Home/index.js
  frontend/src/routing/Redirection.js
Labels: enhancement

#12 Feat/playlist fetch
  backend/app/__init__.py
Labels: enhancement

#18 Feat/docker backend frontend/19
  backend/Dockerfile
  backend/requirements.txt
  docker-compose.yml
  frontend/.dockerignore
  frontend/Dockerfile
Labels: enhancement

#14 Code Freeze - Sprint 1
  .gitignore
  backend/Dockerfile
  backend/app/__init__.py
  backend/app/emotionDetection.py
  backend/requirements.txt
  docker-compose.yml
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/auth/Auth.js
  frontend/src/auth/Spotify.js
  frontend/src/index.css
  frontend/src/layouts/Capture/capture.scss
  frontend/src/layouts/Capture/index.js
  frontend/src/layouts/Capture/webcam.js
  frontend/src/layouts/Capture/webcam.scss
  frontend/src/layouts/Home/home.scss
  frontend/src/layouts/Home/index.js
  frontend/src/layouts/Login/index.js
  frontend/src/layouts/Welcome/index.js
  frontend/src/layouts/Welcome/welcome.scss
  frontend/src/logo.svg
  frontend/src/routing/PrivateRoute.js
  frontend/src/routing/PublicRoute.js
  frontend/src/routing/Redirection.js
Labels: enhancement

#17 Added emotion API call to frontend
  backend/app/__init__.py
  backend/requirements.txt
  frontend/src/layouts/Capture/index.js
  frontend/src/layouts/Capture/webcam.js
Labels: enhancement

#23 add nginx container
  docker-compose.yml
  user_conf.d/nginx-conf.conf
Labels: enhancement

#24 add cadvisor container and clean requirements.txt
  backend/Dockerfile
  backend/app/__init__.py
  backend/requirements.txt
  docker-compose.yml
  requirements.txt
Labels: enhancement

#27 add linting automate check
  .github/workflows/lint.yml
  backend/app/__init__.py
  backend/app/emotionDetection.py
  backend/wsgi.py
Labels: enhancement

#29 14 web api integration
  backend/app/__init__.py
  frontend/package-lock.json
  frontend/src/components/PlaylistTop/index.js
  frontend/src/components/SongList/index.js
  frontend/src/layouts/Capture/capture.scss
  frontend/src/layouts/Capture/index.js
  frontend/src/layouts/Home/home.scss
  frontend/src/layouts/Home/index.js
Labels: enhancement

#28 Code Freeze - Sprint 2
  .github/workflows/lint.yml
  backend/Dockerfile
  backend/app/__init__.py
  backend/app/emotionDetection.py
  backend/requirements.txt
  backend/wsgi.py
  docker-compose.yml
  frontend/package-lock.json
  frontend/src/components/PlaylistTop/index.js
  frontend/src/components/SongList/index.js
  frontend/src/layouts/Capture/capture.scss
  frontend/src/layouts/Capture/index.js
  frontend/src/layouts/Capture/webcam.js
  frontend/src/layouts/Home/home.scss
  frontend/src/layouts/Home/index.js
  requirements.txt
  user_conf.d/nginx-conf.conf
Labels: enhancement

#34 33 deployment bugs
  frontend/Dockerfile
  user_conf.d/nginx-conf.conf
Labels: bug

#40 36 migrate ml to ec2
  .gitignore
  backend/Dockerfile
  backend/app/__init__.py
  emotion-detection/Dockerfile
  emotion-detection/app/__init__.py
  emotion-detection/app/emotionDetection.py
  emotion-detection/docker-compose.yml
  emotion-detection/requirements.txt
  emotion-detection/user_conf.d/nginx-conf.conf
  emotion-detection/wsgi.py
Labels: bug, enhancement

#42 added cadvisor to ml
  emotion-detection/docker-compose.yml
Labels: enhancement

#44 Feat/prometheus grafana/43
  docker-compose.yml
  prometheus.yml
Labels: enhancement

#49 fix grafana endpoint, change frontend to port 6000
  docker-compose.yml
  frontend/Dockerfile
Labels: bug

#48 add endpoint testing
  test.sh
Labels: enhancement, testing

#50 15 implement db
  .gitignore
  backend/app/__init__.py
  backend/requirements.txt
  docker-compose.yml
  frontend/src/layouts/Welcome/index.js
  init-db.js
Labels: enhancement

#52 47 access refresh token
  backend/app/__init__.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/auth/Spotify.js
  frontend/src/components/PlaylistTop/index.js
  frontend/src/components/SongList/index.js
  frontend/src/layouts/Home/index.js
  frontend/src/layouts/Loading/index.js
  frontend/src/layouts/Result/index.js
  frontend/src/layouts/Welcome/index.js
Labels: bug

#53 Final Spike!
  .gitignore
  backend/Dockerfile
  backend/app/__init__.py
  backend/requirements.txt
  docker-compose.yml
  emotion-detection/Dockerfile
  emotion-detection/app/__init__.py
  emotion-detection/app/emotionDetection.py
  emotion-detection/docker-compose.yml
  emotion-detection/requirements.txt
  emotion-detection/user_conf.d/nginx-conf.conf
  emotion-detection/wsgi.py
  frontend/Dockerfile
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/src/App.js
  frontend/src/auth/Spotify.js
  frontend/src/components/PlaylistTop/index.js
  frontend/src/components/SongList/index.js
  frontend/src/layouts/Capture/index.js
  frontend/src/layouts/Home/index.js
  frontend/src/layouts/Loading/index.js
  frontend/src/layouts/Loading/loading.scss
  frontend/src/layouts/Login/index.js
  frontend/src/layouts/Result/index.js
  frontend/src/layouts/Welcome/index.js
  init-db.js
  prometheus.yml
  test.sh
  user_conf.d/nginx-conf.conf
Labels: enhancement
